version: '3'

services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge