version: '3'

services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
      environment:
      - RAWG_API_KEY=${RAWG_API_KEY}
    container_name: java-app
    networks:
      - app-network
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge